### ISSUE TITLE
Explanation on part of script

### ISSUE THREAD

**Issue by edoardo-cioffi-1997** [mikeferguson/ubr_reloaded#15]
Could you please try to explain this part of code from the file ubr1_calibration/configure/capture.yaml?

```
> features:
>   led_finder:
>     type: robot_calibration/LedFinder
>     action: /gripper_led_action
>     topic: /head_camera/depth_registered/points
>     camera_sensor_name: camera
>     chain_sensor_name: arm
>     threshold: 500.0
>     max_iterations: 25
>     debug_image: false
>     gripper_led_frame: wrist_roll_link
>     poses:
>       - code: 1
>         topic: led1
>         x: 0.0621
>         y: 0.023
>         z: 0.026875
>       - code: 2
>         topic: led2
>         x: 0.027
>         y: 0.023
>         z: 0.026875
>       - code: 4
>         topic: led3
>         x: 0.061
>         y: -0.023
>         z: 0.026875
>       - code: 8
>         topic: led4
>         x: 0.027
>         y: -0.023
>         z: 0.026875
```

**Comment by mikeferguson** [comment]
(Just a note - It looks like you're looking at the ROS 1 config - these configs have changed format for ROS 2 because we can't have these XML-RPC style structures)

This configures a single feature finder, of type `robot_calibration/LedFinder` - the LedFinder needs to have the LED information - on the UBR-1 gripper there are 4 leds which can be switched ON/OFF using the `/gripper_led_action` action server.

For each LED, we have the pose relative to the configured `gripper_led_frame` and a code that turns it on when sent to the `/gripper_led_action` (you'll note, these are all basically bit masked - so you could turn on all LEDs by sending 1 + 2 + 4 + 8, although the LedFinder won't do that). The LedFinder then toggles the LEDs on and off and finds the LED centroids in the colored point cloud, which allows us to align the detected pose with the known pose (relative to the gripper_led_frame)

**Comment by edoardo-cioffi-1997** [comment]
Yes, I am using ROS 1. Those coordinates (x,y,z) are random of do they have a physical meaning?

**Comment by mikeferguson** [comment]
The x,y,z are the pose of each LED relative to the `wrist_roll_link` (as. measured in CAD / physical robot)

**Comment by edoardo-cioffi-1997** [comment]
All right, thanks. And does calibration work if I use some lasers which are NOT directly placed on the robot, rather they are fixed on the walls?

**Comment by mikeferguson** [comment]
> does calibration work if I use some lasers which are NOT directly placed on the robot, rather they are fixed on the walls?

Possibly? That's a really broad question, I have no idea what your full setup is...

**Comment by edoardo-cioffi-1997** [comment]
If it's not too much trouble, I will share the setup with you within some days

**Comment by mikeferguson** [comment]
I'd suggest if you're having issues setting up your calibration to open an issue on https://github.com/mikeferguson/robot_calibration.
